addSbtPlugin("com.geirsson"          % "sbt-ci-release" % "1.4.31")
addSbtPlugin("de.heikoseeberger"     % "sbt-header"     % "5.2.0")
addSbtPlugin("com.lightbend.paradox" % "sbt-paradox"    % "0.6.5")
addSbtPlugin("com.typesafe.sbt"      % "sbt-site"       % "1.4.0")
addSbtPlugin("com.typesafe.sbt"      % "sbt-ghpages"    % "0.6.3")
addSbtPlugin("com.timushev.sbt"      % "sbt-updates"    % "0.4.2")
