addSbtPlugin("com.jsuereth"       % "sbt-pgp"         % "1.1.2")
addSbtPlugin("com.github.gseitz"  % "sbt-release"     % "1.0.9")
addSbtPlugin("org.xerial.sbt"     % "sbt-sonatype"    % "2.0")
addSbtPlugin("com.timushev.sbt"   % "sbt-updates"     % "0.3.4")
addSbtPlugin("de.heikoseeberger"  % "sbt-header"      % "5.0.0")
