addSbtPlugin("com.geirsson"          % "sbt-ci-release" % "1.2.6")
addSbtPlugin("de.heikoseeberger"     % "sbt-header"     % "5.2.0")
addSbtPlugin("com.lightbend.paradox" % "sbt-paradox"    % "0.5.5")
addSbtPlugin("com.typesafe.sbt"      % "sbt-site"       % "1.4.0")
addSbtPlugin("com.typesafe.sbt"      % "sbt-ghpages"    % "0.6.3")
